left:
    
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50       

    cartesian_motion_controller:
        type: "position_controllers/CartesianMotionController"
        end_effector_link: "left_arm_link8"
        robot_base_link: "left_arm_link0"
        target_frame_topic: "robot_goal"
        joints:
            - left_arm_joint1
            - left_arm_joint2
            - left_arm_joint3
            - left_arm_joint4
            - left_arm_joint5
            - left_arm_joint6
            - left_arm_joint7

        pd_gains:
            trans_x: {p: 10.0, i: 0.0, d: 0.0}
            trans_y: {p: 10.0, i: 0.0, d: 0.0}
            trans_z: {p: 10.0, i: 0.0, d: 0.0}
            rot_x: {p: 10.0, i: 0.0, d: 0.0}
            rot_y: {p: 10.0, i: 0.0, d: 0.0}
            rot_z: {p: 10.0, i: 0.0, d: 0.0}

    motion_control_handle:
        type: "cartesian_controllers/MotionControlHandle"
        end_effector_link: "left_arm_link8"
        robot_base_link: "left_arm_link0"
        target_frame_topic: "/left/robot_goal"
        joints:
            - left_arm_joint1
            - left_arm_joint2
            - left_arm_joint3
            - left_arm_joint4
            - left_arm_joint5
            - left_arm_joint6
            - left_arm_joint7

right:

    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50
            
    cartesian_motion_controller:
        type: "position_controllers/CartesianMotionController"
        end_effector_link: "right_arm_link8"
        robot_base_link: "right_arm_link0"
        target_frame_topic: "robot_goal"
        joints:
            - right_arm_joint1
            - right_arm_joint2
            - right_arm_joint3
            - right_arm_joint4
            - right_arm_joint5
            - right_arm_joint6
            - right_arm_joint7

        pd_gains:
            trans_x: {p: 10.0, i: 0.0, d: 0.0}
            trans_y: {p: 10.0, i: 0.0, d: 0.0}
            trans_z: {p: 10.0, i: 0.0, d: 0.0}
            rot_x: {p: 10.0, i: 0.0, d: 0.0}
            rot_y: {p: 10.0, i: 0.0, d: 0.0}
            rot_z: {p: 10.0, i: 0.0, d: 0.0}

    motion_control_handle:
        type: "cartesian_controllers/MotionControlHandle"
        end_effector_link: "right_arm_link8"
        robot_base_link: "right_arm_link0"
        target_frame_topic: "/right/robot_goal"
        joints:
            - right_arm_joint1
            - right_arm_joint2
            - right_arm_joint3
            - right_arm_joint4
            - right_arm_joint5
            - right_arm_joint6
            - right_arm_joint7