panda:

  joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

  joint_group_position_controller:
    type: effort_controllers/JointGroupPositionController
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
    joint1: 
      pid: {p: 3000.0, i: 10.0, d: 25.0}
    joint2: 
      pid: {p: 3000.0, i: 10.0, d: 30.0}
    joint3: 
      pid: {p: 3000.0, i: 10.0, d: 30.0}
    joint4: 
      pid: {p: 3000.0, i: 10.0, d: 50.0}
    joint5: 
      pid: {p: 3000.0, i: 10.0, d:  8.0}
    joint6: 
      pid: {p: 3000.0, i:  1.0, d:  5.0}
    joint7: 
      pid: {p: 3000.0, i: 10.0, d:  4.0}

  cartesian_motion_controller:
    type: "position_controllers/CartesianMotionController"
    end_effector_link: "link8"
    robot_base_link: "link0"
    target_frame_topic: "target_frame"
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7

    pd_gains:
      trans_x: {p: 10.0}
      trans_y: {p: 10.0}
      trans_z: {p: 10.0}
      rot_x: {p: 1.0}
      rot_y: {p: 1.0}
      rot_z: {p: 1.0}

  cartesian_force_controller:
    type: "position_controllers/CartesianForceController"
    end_effector_link: "link8"
    robot_base_link: "link0"
    ft_sensor_ref_link: "link7"
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7

    pd_gains:
      trans_x: {p: 0.05}
      trans_y: {p: 0.05}
      trans_z: {p: 0.05}
      rot_x: {p: 0.01}
      rot_y: {p: 0.01}
      rot_z: {p: 0.01}

  cartesian_compliance_controller:
    type: "position_controllers/CartesianComplianceController"
    end_effector_link: "link8"    # All links below must come before this link
    robot_base_link: "link0"
    ft_sensor_ref_link: "link7"
    compliance_ref_link: "link8"
    target_frame_topic: "target_frame"
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint8

    stiffness:  # w.r.t. compliance_ref_link
      trans_x: 500
      trans_y: 500
      trans_z: 500
      rot_x: 100
      rot_y: 100
      rot_z: 100

    pd_gains:
      trans_x: {p: 0.05}
      trans_y: {p: 0.05}
      trans_z: {p: 0.05}
      rot_x: {p: 0.01}
      rot_y: {p: 0.01}
      rot_z: {p: 0.01}

  motion_control_handle:
    type: "cartesian_controllers/MotionControlHandle"
    end_effector_link: "link8"
    robot_base_link: "link0"
    target_frame_topic: "/my_cartesian_motion_controller/target_frame"
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7

  joint_to_cartesian_controller:
    type: "cartesian_controllers/JointControllerAdapter"
    end_effector_link: "link8"
    robot_base_link: "link0"
    target_frame_topic: "/my_cartesian_motion_controller/target_frame"
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7

    joint_limits:
      joint1:
        has_velocity_limits: true
        max_velocity: 3.15
        has_acceleration_limits: true
        max_acceleration: 10.0
      joint2:
        has_velocity_limits: true
        max_velocity: 3.15
        has_acceleration_limits: true
        max_acceleration: 10.0
      joint3:
        has_velocity_limits: true
        max_velocity: 3.15
        has_acceleration_limits: true
        max_acceleration: 10.0
      joint4:
        has_velocity_limits: true
        max_velocity: 3.2
        has_acceleration_limits: true
        max_acceleration: 10.0
      joint5:
        has_velocity_limits: true
        max_velocity: 3.2
        has_acceleration_limits: true
        max_acceleration: 10.0
      joint6:
        has_velocity_limits: true
        max_velocity: 3.2
        has_acceleration_limits: true
        max_acceleration: 10.0

  joint_to_cartesian_controller/joint_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7

  joint_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
