panda:
    
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

    cartesian_motion_controller:
        type: "position_controllers/CartesianMotionController"
        robot_description_name: "/robot_description"
        end_effector_link: "panda_link8"
        robot_base_link: "panda_link0"
        target_frame_topic: "target_frame"
        joints:
            - panda_joint1
            - panda_joint2
            - panda_joint3
            - panda_joint4
            - panda_joint5
            - panda_joint6
            - panda_joint7

        pd_gains:
            trans_x: {p: 10.0, i: 0.0, d: 0.0}
            trans_y: {p: 10.0, i: 0.0, d: 0.0}
            trans_z: {p: 10.0, i: 0.0, d: 0.0}
            rot_x: {p: 10.0, i: 0.0, d: 0.0}
            rot_y: {p: 10.0, i: 0.0, d: 0.0}
            rot_z: {p: 10.0, i: 0.0, d: 0.0}

    motion_control_handle:
        type: "cartesian_controllers/MotionControlHandle"
        robot_description_name: "/robot_description"
        end_effector_link: "panda_link8"
        robot_base_link: "panda_link0"
        target_frame_topic: "/panda/cartesian_motion_controller/target_frame"
        joints:
            - panda_joint1
            - panda_joint2
            - panda_joint3
            - panda_joint4
            - panda_joint5
            - panda_joint6
            - panda_joint7


left:
    
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

    cartesian_motion_controller:
        type: "position_controllers/CartesianMotionController"
        robot_description_name: "/left/robot_description"
        end_effector_link: "left_link8"
        robot_base_link: "left_link0"
        target_frame_topic: "target_frame"
        joints:
            - left_joint1
            - left_joint2
            - left_joint3
            - left_joint4
            - left_joint5
            - left_joint6
            - left_joint7

        pd_gains:
            trans_x: {p: 10.0, i: 0.0, d: 0.0}
            trans_y: {p: 10.0, i: 0.0, d: 0.0}
            trans_z: {p: 10.0, i: 0.0, d: 0.0}
            rot_x: {p: 10.0, i: 0.0, d: 0.0}
            rot_y: {p: 10.0, i: 0.0, d: 0.0}
            rot_z: {p: 10.0, i: 0.0, d: 0.0}

    motion_control_handle:
        type: "cartesian_controllers/MotionControlHandle"
        robot_description_name: "/left/robot_description"
        end_effector_link: "left_link8"
        robot_base_link: "left_link0"
        target_frame_topic: "/left/cartesian_motion_controller/target_frame"
        joints:
            - left_joint1
            - left_joint2
            - left_joint3
            - left_joint4
            - left_joint5
            - left_joint6
            - left_joint7


right:
    
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

    cartesian_motion_controller:
        type: "position_controllers/CartesianMotionController"
        robot_description_name: "/right/robot_description"
        end_effector_link: "right_link8"
        robot_base_link: "right_link0"
        target_frame_topic: "target_frame"
        joints:
            - right_joint1
            - right_joint2
            - right_joint3
            - right_joint4
            - right_joint5
            - right_joint6
            - right_joint7

        pd_gains:
            trans_x: {p: 10.0, i: 0.0, d: 0.0}
            trans_y: {p: 10.0, i: 0.0, d: 0.0}
            trans_z: {p: 10.0, i: 0.0, d: 0.0}
            rot_x: {p: 10.0, i: 0.0, d: 0.0}
            rot_y: {p: 10.0, i: 0.0, d: 0.0}
            rot_z: {p: 10.0, i: 0.0, d: 0.0}

    motion_control_handle:
        type: "cartesian_controllers/MotionControlHandle"
        robot_description_name: "/right/robot_description"
        end_effector_link: "right_link8"
        robot_base_link: "right_link0"
        target_frame_topic: "/right/cartesian_motion_controller/target_frame"
        joints:
            - right_joint1
            - right_joint2
            - right_joint3
            - right_joint4
            - right_joint5
            - right_joint6
            - right_joint7