panda:

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  joint_group_position_controller:
    type: effort_controllers/JointGroupPositionController
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
    joint1: 
      pid: {p: 3000.0, i: 10.0, d: 25.0}
    joint2: 
      pid: {p: 3000.0, i: 10.0, d: 30.0}
    joint3: 
      pid: {p: 3000.0, i: 10.0, d: 30.0}
    joint4: 
      pid: {p: 3000.0, i: 10.0, d: 50.0}
    joint5: 
      pid: {p: 3000.0, i: 10.0, d:  8.0}
    joint6: 
      pid: {p: 3000.0, i:  1.0, d:  5.0}
    joint7: 
      pid: {p: 3000.0, i: 10.0, d:  4.0}
